# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "terminal-table", "~> 1.8"

gem "csv", "~> 3.1"

gem "text-table", "~> 1.2"

gem "json", "~> 2.3"

gem "tty-font", "~> 0.5.0"

gem "test-unit", "~> 3.3"
